#pragma once

#define FONT_FILE_NAME "FFFFORWA.TTF"

#define WINDOW_HEIGHT 600
#define WINDOW_WIDTH 800

#define SIMULATION_HEIGHT 100
#define SIMULATION_WIDTH 100

#define CAMERA_SPEED 200

#define ZOOM_SPEED 2

#define TEXT_BUFFER_SIZE 100
